server:
  port: 8000

spring:
  application:
    name: imooclambda-lesson04
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring_boot_lambda?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Root2019
      driver-class-name: com.mysql.jdbc.Driver
      #      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1


